name = "HEPExampleProject"
uuid = "f779019a-d216-4ac1-8c1a-8c09799cc4e6"
authors = ["Uwe Hernandez Acosta <u.hernandez@hzdr.de>"]
version = "0.0.1-DEV"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[weakdeps]
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"

[extensions]
HEPExampleProjectMakieExt = "Makie"
HEPExampleProjectPlotsExt = ["Plots", "RecipesBase"]

[compat]
Makie = "0.22.9, 0.23"
Plots = "1"
Random = "1"
RecipesBase = "1"
julia = "1.10"
