#/bin/bash

##  Must be run from same directory:
# ./make.sh && ./hepexample

set -e

# Binaries generated by juliac may segfault if JULIA_CPU_TARGET is set:
unset JULIA_CPU_TARGET

jlbindir=`julia-1.12 -e 'println(dirname(Sys.BINDIR))'`

julia-1.12 --project=. -e 'import Pkg; Pkg.instantiate()'

julia-1.12 --project=. "$jlbindir/share/julia/juliac.jl" --experimental --trim=unsafe-warn --output-exe hepexample hepexample.jl
